### ISSUE TITLE
Name for Assignments, Comparisons etc

### ISSUE THREAD

**Issue by conradludgate** [MathsNL/MNL#1]
In standard notation, I'm not sure whether we can describe equivalence or comparison as an operation. `2 + 3` doesn't 'feel' the same as `f(x) = g(x)`. 

Similarly, defining functions or variables using assignments also doesn't feel like an operation and I don't think should be described as one.

@qntmCharles You probably no more about this than I do. Are these operations? Or can you think of a fitting name for these. In computer science they are commonly known as operations so I'm kinda conflicted.

**Comment by conradludgate** [comment]
Maybe the term relation could be applicable

**Comment by conradludgate** [comment]
Thinking about it a bit more, comparisons are operations. But declaration and assignment still need a name

**Comment by qntmCharles** [comment]
Declaration is the same as assignment, and I think they're their own 'thing'. For our notation, I think f(x) := <actual function> is a suitable 'thing' to be standalone and not an operation. 

Personally, I think relations are different to equivalence. 3+2 = 5 is an equivalence. Similarly, given two functions f(x) := x^2+2 and g(x) := x^2+2, g(x) = f(x) is a relation, though it could be viewed as an equivalence, too. However, I do see what you mean by 'they don't feel the same'. In the case of 3+2=5, it feels like = is almost 'carrying out' the mathematics to produce 5 from 3+2. Whereas with g(x) = f(x), it feels like you're identifying that they're the same. Perhaps in the case g(x) = f(x), the equals is an identity? That'd make the difference clear enough. 3+2=5 is *equating* something. g(x) = f(x) is *identifying* (or, sort of, relating) something. In fact, I'd say 3+2=5 is an equivalence. g(x) = f(x) is an identity. 3+2=4+1 is a relation. Is that clear enough?

**Comment by conradludgate** [comment]
Yeah that makes sense to me. I guess we would want different notations for each then, if we're gonna make it context free anyway. Such as `g(x) == f(x)` and `3 + 2 -> 5`

**Comment by qntmCharles** [comment]
I think a double equals '==' is suitable for equivalence. That is, 3+2==4+1. I don't think <=> should be used since this is for double implication. := should be used for assignment/declaration, f(x) := x^2+2. I think 3+2=5 is a suitable use of the equals operator, since that's how it's generally used and we don't want to completely change everything - that'd make MNL inaccessible. f(5) -> 5 is function application, e.g. if f(x) := x^2+2, then f(5) -> 27.

**Comment by qntmCharles** [comment]
To clarify;

=== is identity
== is equivalence
= is your bog standard equals
-> is application
:= is declaration/assignment

What I still can't decide is whether relation is equivalence or identity. I'm leaning identity.

**Comment by conradludgate** [comment]
On a side note, as a hand written version, should adding an equals be the same as adding another line to the symbol. Such as triple equals in standard notation, or less than or equal to.

And relation covers things like inequalities, yes?

**Comment by qntmCharles** [comment]
Yes I think adding an equals adds a line. === with four lines may be slightly messy though. To be honest, I'm not sure what relation covers. It doesn't feel entirely necessary as its own thing, but I'm not sure how it's covered by the other operators.

**Comment by qntmCharles** [comment]
Perhaps all of the operators we've discussed are relations. All those operators can be *classed* as relations. Unless there's an example we can't cover, I don't think anymore relation symbols are necessary, other than perhaps != for not equals (the normal written notation of a crossed = is acceptable, I'd say.)

**Comment by qntmCharles** [comment]
See relations.md
